# Generated by Django 3.2.5 on 2021-07-10 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domicilio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_os', models.CharField(max_length=50)),
                ('plan_cobertura', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_OS', models.BooleanField(default=False)),
                ('tipo_sangre', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('domicilio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direccion', to='domicilio.direccion')),
                ('obra_social', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obra_social', to='modelsGeneral.obrasocial')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nac', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField(auto_now=True)),
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('odontologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odontologo', to='modelsGeneral.odontologo')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paciente', to='modelsGeneral.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers3', to='modelsGeneral.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_resp', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers', to='modelsGeneral.persona')),
            ],
        ),
        migrations.AddField(
            model_name='paciente',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers1', to='modelsGeneral.persona'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='responsable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to='modelsGeneral.responsable'),
        ),
        migrations.AddField(
            model_name='odontologo',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pers2', to='modelsGeneral.persona'),
        ),
    ]
